// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuralCourtyard.Models.Infrastructure;

#nullable disable

namespace RuralCourtyard.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231219213524_NewDataForProduct")]
    partial class NewDataForProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Favorites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "red",
                            Cost = 300m,
                            Description = "Зимостойкое, устойчивое к болезням кустистое растение с чашевидными ярко-розовыми цветками диаметром 8–10 см. Цвести роза начинает рано (в начале лета) и продолжает благоухать до поздней осени. В аромате чувствуются тонкие нотки меда и миндаля.Почва: Розы любят нейтральный (рН 6), богатый гумусом, умеренно-влажный и рыхлый грунт.Место посадки: Пионовидные розы предпочитают полутень. При этом участок должен освещаться солнечными лучам не менее 3 часов в сутки. Под большими деревьями или на северной стороне здания растение цвести практически не будет.Подкормка: Пионовидным розам требуются минеральные удобрения, содержащие азот, фосфор, калий, магний, железо и микроэлементы. В первой половине лета вносите азотные удобрения, в период формирования бутонов — фосфор и калий, свежий навоз.Цветение: зацветают в конце мая–начале июня. ",
                            ImageLink = "mary-rose.png",
                            Name = "Мэри роуз"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "red",
                            Cost = 300m,
                            Description = "Зимостойкое, устойчивое к болезням кустистое растение с чашевидными ярко-розовыми цветками диаметром 8–10 см. Цвести роза начинает рано (в начале лета) и продолжает благоухать до поздней осени. В аромате чувствуются тонкие нотки меда и миндаля.Почва: Розы любят нейтральный (рН 6), богатый гумусом, умеренно-влажный и рыхлый грунт.Место посадки: Пионовидные розы предпочитают полутень. При этом участок должен освещаться солнечными лучам не менее 3 часов в сутки. Под большими деревьями или на северной стороне здания растение цвести практически не будет.Подкормка: Пионовидным розам требуются минеральные удобрения, содержащие азот, фосфор, калий, магний, железо и микроэлементы. В первой половине лета вносите азотные удобрения, в период формирования бутонов — фосфор и калий, свежий навоз.Цветение: зацветают в конце мая–начале июня. ",
                            ImageLink = "mary-rose.png",
                            Name = "Мэри роуз"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Color = "red",
                            Cost = 300m,
                            Description = "Зимостойкое, устойчивое к болезням кустистое растение с чашевидными ярко-розовыми цветками диаметром 8–10 см. Цвести роза начинает рано (в начале лета) и продолжает благоухать до поздней осени. В аромате чувствуются тонкие нотки меда и миндаля.Почва: Розы любят нейтральный (рН 6), богатый гумусом, умеренно-влажный и рыхлый грунт.Место посадки: Пионовидные розы предпочитают полутень. При этом участок должен освещаться солнечными лучам не менее 3 часов в сутки. Под большими деревьями или на северной стороне здания растение цвести практически не будет.Подкормка: Пионовидным розам требуются минеральные удобрения, содержащие азот, фосфор, калий, магний, железо и микроэлементы. В первой половине лета вносите азотные удобрения, в период формирования бутонов — фосфор и калий, свежий навоз.Цветение: зацветают в конце мая–начале июня. ",
                            ImageLink = "mary-rose.png",
                            Name = "Мэри роуз"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Color = "red",
                            Cost = 300m,
                            Description = "Зимостойкое, устойчивое к болезням кустистое растение с чашевидными ярко-розовыми цветками диаметром 8–10 см. Цвести роза начинает рано (в начале лета) и продолжает благоухать до поздней осени. В аромате чувствуются тонкие нотки меда и миндаля.Почва: Розы любят нейтральный (рН 6), богатый гумусом, умеренно-влажный и рыхлый грунт.Место посадки: Пионовидные розы предпочитают полутень. При этом участок должен освещаться солнечными лучам не менее 3 часов в сутки. Под большими деревьями или на северной стороне здания растение цвести практически не будет.Подкормка: Пионовидным розам требуются минеральные удобрения, содержащие азот, фосфор, калий, магний, железо и микроэлементы. В первой половине лета вносите азотные удобрения, в период формирования бутонов — фосфор и калий, свежий навоз.Цветение: зацветают в конце мая–начале июня. ",
                            ImageLink = "mary-rose.png",
                            Name = "Мэри роуз"
                        });
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Cart", b =>
                {
                    b.HasOne("RuralCourtyard.Models.Infrastructure.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuralCourtyard.Models.Infrastructure.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Favorites", b =>
                {
                    b.HasOne("RuralCourtyard.Models.Infrastructure.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuralCourtyard.Models.Infrastructure.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RuralCourtyard.Models.Infrastructure.Product", b =>
                {
                    b.HasOne("RuralCourtyard.Models.Infrastructure.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
